dataset:
  conditioning:
    enabled: true
    normalize: true
    property: mu_clean
  dataset_name: qme14s
  processed_data_dir: /blue/mingjieliu/jiruijin/diffusion/FlowMol/data/qme14s
  use_first_half_training_set: false
model:
  dropout: 0.0
  n_atom_types: 14
  n_tasks: 1
  num_layers: 3
  pooling_type: mean
  scalar_size: 256
  vector_size: 16
mol_fm:
  parameterization: ctmc
  prior_config:
    a:
      align: false
      kwargs: {}
      type: ctmc
    c:
      align: false
      kwargs: {}
      type: ctmc
    e:
      align: false
      kwargs: {}
      type: ctmc
    x:
      align: true
      kwargs:
        std: 1.0
      type: centered-normal
training:
  batch_size: 128
  learning_rate: 0.001
  num_workers: 4
  output_dir: model_output_qme14s
  scheduler_factor: 0.5
  scheduler_patience: 10
  trainer_args:
    accelerator: gpu
    accumulate_grad_batches: 1
    devices: 1
    max_epochs: 1000
    num_nodes: 1
  weight_decay: 0.0001
